# Generated by Django 5.2.4 on 2025-08-12 20:52

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tipo_de_contenido',
            },
        ),
        migrations.CreateModel(
            name='TipoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'crear_modulo',
            },
        ),
        migrations.AddField(
            model_name='tema',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portada/'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_entrega', models.CharField(blank=True, choices=[('', 'Seleccionar'), ('ondemand', 'On Demand'), ('envivo', 'En Vivo')], default='', max_length=20, null=True)),
                ('dias_disponibles', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=52, null=True)),
                ('mostrar_en_vip', models.BooleanField(default=False, verbose_name='Mostrar en VIP')),
                ('mostrar_en_business', models.BooleanField(default=False, verbose_name='Mostrar en Business')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='packages.tema')),
                ('tipo_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='packages.tipocontenido')),
            ],
        ),
        migrations.CreateModel(
            name='Temario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temarios', to='packages.curso')),
                ('tipo_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temarios', to='packages.tipomodulo')),
            ],
        ),
    ]
