# Generated by Django 5.2.4 on 2025-07-28 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='packages.tema')),
            ],
        ),
    ]
