# Generated by Django 5.2.4 on 2025-07-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_capitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='tipo',
            field=models.CharField(choices=[('ondemand', 'On Demand'), ('envivo', 'En Vivo')], default='ondemand', max_length=20),
        ),
    ]
