# Generated by Django 5.2.4 on 2025-08-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_tipocontenido_tipomodulo_tema_portada_curso_temario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
