# Generated by Django 5.2.4 on 2025-08-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_curso_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomodulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
