# Generated by Django 5.2.4 on 2025-07-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_capitulo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='tipo_contenido',
            field=models.CharField(choices=[('', 'Seleccionar'), ('masterclass', 'Masterclass'), ('curso', 'Curso')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='tipo_entrega',
            field=models.CharField(choices=[('', 'Seleccionar'), ('ondemand', 'On Demand'), ('envivo', 'En Vivo')], default='', max_length=20),
        ),
    ]
