# Generated by Django 5.2.4 on 2025-07-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_remove_capitulo_tipo_capitulo_tipo_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='tipo_contenido',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('masterclass', 'Masterclass'), ('curso', 'Curso')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('ondemand', 'On Demand'), ('envivo', 'En Vivo')], default='', max_length=20, null=True),
        ),
    ]
