# Generated by Django 5.2.4 on 2025-08-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_tipomodulo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomodulo',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
