# Generated by Django 5.2.4 on 2025-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_tipomodulo_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomodulo',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
