# Generated by Django 5.2.4 on 2025-07-28 05:42

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_capitulo_tipo_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='dias_disponibles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=52, null=True),
        ),
    ]
