# Generated by Django 5.2.4 on 2025-08-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_tipomodulo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomodulo',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.curso'),
        ),
    ]
