# Generated by Django 5.2.4 on 2025-08-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_temabusiness_capitulobusiness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapituloBusiness',
        ),
        migrations.DeleteModel(
            name='TemaBusiness',
        ),
    ]
