# Generated by Django 5.2.4 on 2025-08-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_tipomodulo_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipomodulo',
            old_name='descripcion',
            new_name='descripcion_modulo',
        ),
        migrations.RenameField(
            model_name='tipomodulo',
            old_name='nombre',
            new_name='nombre_modulo',
        ),
    ]
