# Generated by Django 5.2.4 on 2025-08-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_rename_descripcion_tipomodulo_descripcion_modulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='portada',
        ),
    ]
