# Generated by Django 5.2.4 on 2025-08-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_remove_tema_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enlace video', null=True),
        ),
    ]
