# Generated by Django 5.2.4 on 2025-08-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_curso_delete_capitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_modulo', models.CharField(choices=[('modulo_1', 'Módulo 1'), ('modulo_2', 'Módulo 2'), ('modulo_3', 'Módulo 3'), ('modulo_4', 'Módulo 4')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temarios', to='packages.curso')),
            ],
            options={
                'ordering': ['tipo_modulo', 'orden'],
            },
        ),
    ]
