# Generated by Django 5.2.4 on 2025-08-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_tipocontenido_alter_curso_tipo_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_contenido',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('masterclass', 'Masterclass'), ('curso', 'Curso')], default='', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TipoContenido',
        ),
    ]
