# Generated by Django 5.2.4 on 2025-08-12 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_alter_curso_tipo_contenido_delete_tipocontenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Contenido',
                'verbose_name_plural': 'Tipos de Contenido',
            },
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo_contenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='packages.tipocontenido'),
        ),
    ]
