# Generated by Django 5.2.4 on 2025-08-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_tipocontenido_alter_curso_tipo_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocontenido',
            options={},
        ),
        migrations.RemoveField(
            model_name='tipocontenido',
            name='codigo',
        ),
    ]
