# Generated by Django 5.2.4 on 2025-08-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_alter_tipocontenido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocontenido',
            options={'verbose_name': 'Tipo de Contenido', 'verbose_name_plural': 'Tipos de Contenido'},
        ),
    ]
