# Generated by Django 5.2.4 on 2025-08-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_alter_tipocontenido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocontenido',
            options={'verbose_name': 'tipo_de_contenido', 'verbose_name_plural': 'tipos_de_contenido'},
        ),
    ]
