# Generated by Django 5.2.4 on 2025-08-12 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_alter_tipocontenido_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'tipo_de_modulo',
                'verbose_name_plural': 'tipos_de_modulo',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='temario',
            options={'ordering': ['tipo_modulo__orden', 'orden']},
        ),
        migrations.AlterField(
            model_name='temario',
            name='tipo_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temarios', to='packages.tipomodulo'),
        ),
    ]
