# Generated by Django 5.2.4 on 2025-08-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_tipomodulo_alter_temario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipocontenido',
            options={'verbose_name': 'tipo_de_contenido'},
        ),
        migrations.AlterModelOptions(
            name='tipomodulo',
            options={'verbose_name': 'crear_modulo'},
        ),
        migrations.RemoveField(
            model_name='temario',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='tipomodulo',
            name='orden',
        ),
        migrations.AddField(
            model_name='curso',
            name='mostrar_en_business',
            field=models.BooleanField(default=False, help_text='Marcar si el curso debe mostrarse en la página Business', verbose_name='Mostrar en Business'),
        ),
        migrations.AddField(
            model_name='curso',
            name='mostrar_en_vip',
            field=models.BooleanField(default=False, help_text='Marcar si el curso debe mostrarse en la página VIP', verbose_name='Mostrar en VIP'),
        ),
    ]
