# Generated by Django 5.2.4 on 2025-08-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_alter_temario_options_alter_tipocontenido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='mostrar_en_business',
            field=models.BooleanField(default=False, verbose_name='Mostrar en Business'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='mostrar_en_vip',
            field=models.BooleanField(default=False, verbose_name='Mostrar en VIP'),
        ),
    ]
