# Generated by Django 5.2.4 on 2025-08-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_alter_curso_mostrar_en_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portada/'),
        ),
    ]
