# Generated by Django 5.2.4 on 2025-07-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('foto', models.ImageField(upload_to='docentes/')),
            ],
        ),
    ]
