# Generated by Django 5.2.4 on 2025-08-12 23:17

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='clientes/')),
            ],
            options={
                'verbose_name': 'clientes',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='HistoriaVideoBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='historias/', validators=[main.models.validar_tamano_video], verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Historia_videos_business',
                'verbose_name_plural': 'Historia_videos_business',
            },
        ),
        migrations.CreateModel(
            name='marcas_bussines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='marcas/')),
            ],
        ),
        migrations.CreateModel(
            name='membresia_bussines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('nombre_encargado', models.CharField(max_length=100)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('membresia', models.IntegerField(choices=[(1, 'Membresía 2-10'), (2, 'Membresía 11-100'), (3, 'Membresía +100')], default=1)),
            ],
            options={
                'verbose_name': 'Membresía Business',
                'verbose_name_plural': 'Membresías Business',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='membresia_estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=50)),
                ('membresia', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='membresia_free_bussines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('nombre_encargado', models.CharField(max_length=100)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='membresia_profesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=50)),
                ('membresia', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MembresiaVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta_cabecera', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la membresía')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('beneficios', models.TextField(blank=True, help_text='Lista de beneficios, separados por saltos de línea.', null=True, verbose_name='Beneficios')),
                ('oferta', models.CharField(blank=True, help_text='Ej: Descuento, Black Friday, etc.', max_length=100, null=True, verbose_name='Oferta especial')),
            ],
            options={
                'verbose_name': 'Membresía VIP',
                'verbose_name_plural': 'Membresías VIP',
            },
        ),
        migrations.CreateModel(
            name='prueba_gratuita_vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'docentes', 'verbose_name_plural': 'docentes'},
        ),
        migrations.AddField(
            model_name='docente',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='docentes/'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
