# Generated by Django 5.2.4 on 2025-08-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('foto', models.ImageField(upload_to='docentes/')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='estudiantes/')),
            ],
        ),
        migrations.CreateModel(
            name='EstudiantesBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='estudiantes/')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('video', models.FileField(blank=True, null=True, upload_to='historias/', verbose_name='Video')),
                ('reel', models.URLField(blank=True, null=True, verbose_name='Enlace al Reel')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaVideoBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('video', models.FileField(blank=True, null=True, upload_to='historias/', verbose_name='Video')),
                ('reel', models.URLField(blank=True, null=True, verbose_name='Enlace al Reel')),
            ],
        ),
        migrations.CreateModel(
            name='membresia_bussines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('nombre_encargado', models.CharField(max_length=100)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='membresia_estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=50)),
                ('membresia', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='membresia_free_bussines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('nombre_encargado', models.CharField(max_length=100)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='membresia_profesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=50)),
                ('membresia', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='prueba_gratuita_vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=50)),
            ],
        ),
    ]
