# Generated by Django 5.2.4 on 2025-07-25 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historiavideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpcionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_clase', models.CharField(choices=[('masterclass', 'Masterclass'), ('curso', 'Curso')], max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('dias', models.CharField(blank=True, max_length=200)),
                ('subtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_clase', to='main.subtema')),
            ],
        ),
        migrations.AddField(
            model_name='subtema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='main.tema'),
        ),
        migrations.CreateModel(
            name='TipoContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('en_vivo', 'En Vivo'), ('on_demand', 'Bajo Demanda')], max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('dias', models.CharField(blank=True, max_length=200)),
                ('subtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_contenido', to='main.subtema')),
            ],
        ),
    ]
