# Generated by Django 5.2.4 on 2025-08-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_docentebusiness_estudiantes_estudiantesbusiness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='clientes/')),
            ],
            options={
                'verbose_name': 'clientes',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.DeleteModel(
            name='DocenteBusiness',
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
        migrations.DeleteModel(
            name='EstudiantesBusiness',
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'docentes', 'verbose_name_plural': 'docentes'},
        ),
    ]
