# Generated by Django 5.2.4 on 2025-08-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_docentebusiness_estudiantes_estudiantesbusiness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='marcas_bussines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='marcas/')),
            ],
        ),
    ]
