# Generated by Django 5.2.4 on 2025-08-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clientes_historiavideobusiness_marcas_bussines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_corporativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contenidos', models.PositiveIntegerField(default=0, verbose_name='Número de contenidos')),
                ('numero_cursos', models.PositiveIntegerField(default=0, verbose_name='Número de cursos')),
                ('numero_profesionales', models.PositiveIntegerField(default=0, verbose_name='Número de profesionales')),
                ('numero_empresas_lideres', models.PositiveIntegerField(default=0, verbose_name='Número de empresas líderes')),
            ],
            options={
                'verbose_name': 'Datos corporativos',
                'verbose_name_plural': 'Datos corporativos',
            },
        ),
    ]
