# Generated by Django 5.2.4 on 2025-08-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clientes_delete_docentebusiness_delete_estudiantes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriaVideo',
        ),
        migrations.AlterModelOptions(
            name='historiavideobusiness',
            options={'verbose_name': 'Historia_videos_business', 'verbose_name_plural': 'Historia_videos_business'},
        ),
        migrations.RemoveField(
            model_name='historiavideobusiness',
            name='nombre',
        ),
        migrations.AddField(
            model_name='docente',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
