# Generated by Django 5.2.4 on 2025-07-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subtema_tema_opcionclase_subtema_tema_tipocontenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='estudiantes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='tipocontenido',
            name='subtema',
        ),
        migrations.DeleteModel(
            name='OpcionClase',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
        migrations.DeleteModel(
            name='Subtema',
        ),
        migrations.DeleteModel(
            name='TipoContenido',
        ),
    ]
