# Generated by Django 5.2.4 on 2025-08-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_marcas_bussines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membresia_bussines',
            options={'ordering': ['nombre_empresa'], 'verbose_name': 'Membresía Business', 'verbose_name_plural': 'Membresías Business'},
        ),
        migrations.AddField(
            model_name='membresia_bussines',
            name='membresia',
            field=models.IntegerField(choices=[(1, 'Membresía 2-10'), (2, 'Membresía 11-100'), (3, 'Membresía +100')], default=1),
        ),
    ]
