# Generated by Django 5.2.4 on 2025-08-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_datos_corporativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_corporativos',
            name='numero_contenidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos_corporativos',
            name='numero_cursos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos_corporativos',
            name='numero_empresas_lideres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos_corporativos',
            name='numero_profesionales',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
