# Generated by Django 5.2.4 on 2025-08-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_historiavideo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembresiaVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la membresía')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('beneficios', models.TextField(help_text='Lista de beneficios, separados por saltos de línea.', verbose_name='Beneficios')),
                ('descuento', models.CharField(blank=True, choices=[('', 'Sin descuento'), ('10', '10%'), ('20', '20%')], max_length=2, null=True, verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Membresía VIP',
                'verbose_name_plural': 'Membresías VIP',
            },
        ),
    ]
