# Generated by Django 5.2.4 on 2025-08-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_datos_corporativos_numero_contenidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_corporativos',
            name='numero_contenidos',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Número de contenidos'),
        ),
        migrations.AlterField(
            model_name='datos_corporativos',
            name='numero_cursos',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Número de cursos'),
        ),
        migrations.AlterField(
            model_name='datos_corporativos',
            name='numero_empresas_lideres',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Número de empresas líderes'),
        ),
        migrations.AlterField(
            model_name='datos_corporativos',
            name='numero_profesionales',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Número de profesionales'),
        ),
    ]
