# Generated by Django 5.2.4 on 2025-07-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paquete_tema_capitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='paquete',
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
