# Generated by Django 5.2.4 on 2025-08-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_membresiavip'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiavip',
            name='oferta',
            field=models.CharField(blank=True, help_text='Ej: Descuento, Black Friday, etc.', max_length=100, null=True, verbose_name='Oferta especial'),
        ),
    ]
