# Generated by Django 5.2.4 on 2025-07-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_tema_paquete_delete_capitulo_delete_paquete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiavideo',
            name='reel',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace al Reel'),
        ),
    ]
