# Generated by Django 5.2.4 on 2025-08-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_membresiavip_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresiavip',
            name='descuento',
        ),
    ]
