# Generated by Django 5.2.4 on 2025-08-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_membresiavip_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiavip',
            name='etiqueta_cabecera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
