# Generated by Django 5.2.4 on 2025-08-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historiavideo_reel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('foto', models.ImageField(upload_to='docentes/')),
            ],
        ),
        migrations.CreateModel(
            name='EstudiantesBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='estudiantes/')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaVideoBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('video', models.FileField(upload_to='historias/', verbose_name='Video')),
                ('reel', models.URLField(blank=True, null=True, verbose_name='Enlace al Reel')),
            ],
        ),
    ]
