# Generated by Django 5.2.4 on 2025-08-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_membresiavip_etiqueta_cabecera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiavideobusiness',
            name='reel',
        ),
        migrations.AlterField(
            model_name='membresiavip',
            name='beneficios',
            field=models.TextField(blank=True, help_text='Lista de beneficios, separados por saltos de línea.', null=True, verbose_name='Beneficios'),
        ),
    ]
