# Generated by Django 5.2.4 on 2025-08-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_historiavideo_nombre_alter_historiavideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiavideobusiness',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historiavideobusiness',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='historias/', verbose_name='Video'),
        ),
    ]
