# Generated by Django 5.2 on 2025-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_historiavideobusiness_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembresiaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=50)),
                ('perfil', models.CharField(max_length=20)),
                ('membresia', models.PositiveIntegerField()),
            ],
        ),
    ]
