# Generated by Django 5.2.4 on 2025-08-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages_business', '0003_temario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursobusiness',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='temabusiness',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
    ]
